name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          TAGS="ghcr.io/dcodesdev/letterspace:${VERSION}"

          # Check if version has a dash (indicating prerelease)
          if [[ ! "$VERSION" == *"-"* ]]; then
            TAGS="$TAGS,ghcr.io/dcodesdev/letterspace:latest"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
